tweaking git-fix-my-fork

diff --git a/git-fix-my-fork b/git-fix-my-fork
--- a/git-fix-my-fork
+++ b/git-fix-my-fork
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e
+
 MYBRANCH="$(git branch --show-current)"
 
 if [ -z "${MYBRANCH}" ]; then
@@ -7,15 +9,26 @@ if [ -z "${MYBRANCH}" ]; then
     exit 1
 fi
 
-if [ "$(git remote -v | grep upstream | grep push -c)" -ne 1 ]; then
+if [ "$(git remote -v | grep -ce "^upstream")" -eq 0 ]; then
     echo "Couldn't find an upstream remote, bailing"
     exit 1
 fi
 
-git switch "upstream/${MYBRANCH}" --detach || echo "Already in detached state"
+DEFAULT_BRANCH="$(gh repo view --json defaultBranchRef | jq -r .defaultBranchRef.name)"
 
-git branch -D "${MYBRANCH}"
+if [ -z "${DEFAULT_BRANCH}" ]; then
+    echo "Couldn't find the default branch using , bailing"
+    echo "Tried this command: gh repo view --json defaultBranchRef"
+    gh repo view --json defaultBranchRef
+    exit 1
+fi
 
-git checkout -b "${MYBRANCH}" && git pull upstream "${MYBRANCH}"
+git fetch upstream || exit 1
+
+echo "Switching to ${DEFAULT_BRANCH}"
+git switch "${DEFAULT_BRANCH}" || exit 1
+
+echo "Resetting to ${DEFAULT_BRANCH}"
+git reset --hard "upstream/${DEFAULT_BRANCH}"
 
 git gc
